from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

def content_bbox(alpha: np.ndarray):
    ys, xs = np.where(alpha > 8)
    if len(xs) == 0:
        return 0, 0, alpha.shape[1], alpha.shape[0]
    return int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1

def feather_mask(mask: Image.Image, radius: float) -> Image.Image:
    return mask.filter(ImageFilter.GaussianBlur(radius))

def masked_layer(img: Image.Image, region_mask: Image.Image) -> Image.Image:
    """Return img with its alpha multiplied by region_mask (both same size)."""
    out = img.copy()
    a = out.getchannel("A")
    m = region_mask.convert("L")
    new_a = Image.fromarray((np.asarray(a, float) * np.asarray(m, float) / 255.0)
                            .clip(0, 255).astype("uint8"))
    out.putalpha(new_a)
    return out

def rect_mask(size, box) -> Image.Image:
    m = Image.new("L", size, 0)
    ImageDraw.Draw(m).rectangle(box, fill=255)
    return m

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", default="lily")
    ap.add_argument("--head", type=float, default=0.36, help="head height as fraction of content")
    ap.add_argument("--arm-y0", type=float, default=0.40)
    ap.add_argument("--arm-y1", type=float, default=0.74)
    ap.add_argument("--arm-w", type=float, default=0.26, help="arm box width as fraction of content")
    args = ap.parse_args()

    d = Path(__file__).resolve().parents[2] / "assets" / "characters" / args.name
    img = Image.open(d / "sprites.png").convert("RGBA")
    W, H = img.size
    alpha = np.asarray(img.getchannel("A"))

    x0, y0, x1, y1 = content_bbox(alpha)
    cw, ch = x1 - x0, y1 - y0

    head_bottom = int(y0 + args.head * ch)
    head_box = (0, 0, W, head_bottom)
    head_mask = rect_mask((W, H), head_box)
    head_mask = feather_mask(head_mask, radius=max(2, ch * 0.02))

    head_alpha = alpha[y0:head_bottom, :]
    hx = np.where(head_alpha.sum(axis=0) > 0)[0]
    head_cx = int((hx.min() + hx.max()) / 2) if len(hx) else (x0 + cw // 2)
    neck = (head_cx, head_bottom)

    ay0 = int(y0 + args.arm_y0 * ch)
    ay1 = int(y0 + args.arm_y1 * ch)
    aw = int(args.arm_w * cw)
    armL_box = (x0, ay0, x0 + aw, ay1)
    armR_box = (x1 - aw, ay0, x1, ay1)
    armL_mask = feather_mask(rect_mask((W, H), armL_box), radius=max(2, cw * 0.03))
    armR_mask = feather_mask(rect_mask((W, H), armR_box), radius=max(2, cw * 0.03))
    shoulderL = (x0 + aw, ay0)
    shoulderR = (x1 - aw, ay0)

    img.save(d / "body.png")
    masked_layer(img, head_mask).save(d / "head.png")
    masked_layer(img, armL_mask).save(d / "armL.png")
    masked_layer(img, armR_mask).save(d / "armR.png")

    frames = json.loads((d / "frames.json").read_text(encoding="utf-8"))
    mouth = frames.get("meta", {}).get("mouth", {"x": 0.5, "y": 0.38, "w": 0.04, "h": 0.04})
    rig = {
        "meta": {"frameWidth": W, "frameHeight": H, "renderScale": 1, "mouth": mouth,
                 "note": "Generated by ai/tools/segment_rig.py"},
        "zorder": ["body", "armL", "armR", "head"],
        "pivots": {
            "neck":      {"x": neck[0] / W,      "y": neck[1] / H},
            "shoulderL": {"x": shoulderL[0] / W, "y": shoulderL[1] / H},
            "shoulderR": {"x": shoulderR[0] / W, "y": shoulderR[1] / H},
        },
    }
    (d / "rig.json").write_text(json.dumps(rig, indent=2), encoding="utf-8")

    prev = img.copy()
    pd = ImageDraw.Draw(prev)
    pd.line([(0, head_bottom), (W, head_bottom)], fill=(0, 200, 0, 255), width=2)
    pd.rectangle(armL_box, outline=(0, 120, 255, 255), width=2)
    pd.rectangle(armR_box, outline=(0, 120, 255, 255), width=2)
    for (px, py) in (neck, shoulderL, shoulderR):
        pd.ellipse([px - 4, py - 4, px + 4, py + 4], fill=(255, 40, 40, 255))
    prev.save(d / "rig_preview.png")

    print(f"head_bottom={head_bottom} neck={neck} shoulderL={shoulderL} shoulderR={shoulderR}")
    print(f"wrote body/head/armL/armR.png, rig.json, rig_preview.png in {d}")

if __name__ == "__main__":
    main()
